### ISSUE TITLE
感觉你写太复杂了，本来挺简单的demo

### ISSUE THREAD

**Issue by liaoyuhanCSDN** [acccco/VueReactiveData#2]
let callback = {
    target: null
}
let defineReactive = function(object, key, value){
    let array = []
    Object.defineProperty(object, key, {
        configurable: true,
        enumerable: true,
        get: function(){
            if(callback.target){
                array.push(callback.target)
            }
            return value
        },
        set: function(newValue){
            if(newValue != value){
                array.forEach((fun)=>fun(newValue, value))
            }
            value = newValue
        }
    })
}
没看懂你说的
当对 object 进行 get 操作(取值操作)的时候，就会往 callback 中存放函数，进行 set 操作(设置值)的时候执行数组中的函数
为什么要定义一个数组，你数组 array.push(callback.target) ,里面不是存着对象的属性吗？怎么又变方法了。你下面那句array.forEach最后遍历出来不是对象的属性吗？属性变成方法？array.forEach((fun)=>fun(newValue, value))。本来挺简单的，你这样一写感觉又复杂了！

**Comment by liaoyuhanCSDN** [comment]
主要是你的这个封装让人摸不着北

**Comment by acccco** [comment]
这还没开始封装，如果这都复杂的话，那么 vue 里面的源码就看不了了，我是按照 vue 的源码简化的。
